[package]
name = "testing"
version = "0.1.0"
edition = "2023_10"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "audited"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.4.3"
alexandria_merkle_tree = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag="cairo-v2.3.0-rc0"  }